license="MIT"

[[mods]]
modId="hurricane"
version="${version}"
displayName="Hurricane"
authors="darkcupid412"
description="Exact per-player Bedrock collision translation for Geyser"

[[mixins]]
config="hurricane.mixins.json"

[[dependencies.hurricane]]
modId="neoforge"
type="required"
versionRange="[26.2.0.15-beta,)"
ordering="NONE"
side="SERVER"

[[dependencies.hurricane]]
modId="minecraft"
type="required"
versionRange="[26.2]"
ordering="NONE"
side="SERVER"

[[dependencies.hurricane]]
modId="geyser_neoforge"
type="optional"
versionRange="[2.11.0-SNAPSHOT,)"
ordering="AFTER"
side="SERVER"

[[dependencies.hurricane]]
modId="floodgate-modded"
type="optional"
versionRange="[2.2.5,)"
ordering="AFTER"
side="SERVER"
